name: Security Scan with Bandit

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  security:
    name: Run Bandit Security Scan
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install bandit

    - name: Run Bandit Scan
      run: |
        bandit -r . -f json -o bandit_output.json
        bandit -r . -ll --exit-zero

    - name: Check for Vulnerabilities
      run: |
        issues=$(bandit -r . --quiet | grep -i ">> Issue")
        if [[ ! -z "$issues" ]]; then
          echo "❌ Vulnerabilities found!"
          echo "$issues"
          exit 1
        else
          echo "✅ No vulnerabilities found."
        fi
